apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-mapping-1660167393371
  namespace: gitops-demo
spec:
  service: quote.gitops-demo:80
  timeout_ms: 3000
  connect_timeout_ms: 3000
  retry_policy:
    retry_on: 5xx
    num_retries: 1
    per_try_timeout: 0.150s
  hostname: "*"
  prefix: /sdfsdfs/
